In [1]:
import numpy as np

In [2]:
a= np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
print(a)

[1 2 3 4]


In [5]:
#Range 
a = np.arange(10)

In [6]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#Comparision between normal range and numpy
b= range(10)

In [10]:
print(b)

range(0, 10)


In [12]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
%timeit[i**2 for i in l]

6.67 µs ± 398 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [16]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
%timeit(a**2)

1.01 µs ± 65.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [25]:
a= np.array([1,2,3,4])

In [26]:
a.ndim

1

In [27]:
a.shape

(4,)

In [21]:
a = np.array([[1,2],[2,3]])
a.ndim

2

In [23]:
a.shape

(2, 2)

In [31]:
a = np.array([[[1,2],[2,4]],[[3,4],[4,5]]])

In [32]:
a.shape

(2, 2, 2)

In [33]:
#1 D = Vector
#2 D = Matrix
#3 D = Tensor

In [34]:
#Function for creating an array
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
b= np.arange(1,10,2)

In [36]:
b

array([1, 3, 5, 7, 9])

In [37]:
a = np.linspace(1,10,6)
a

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [38]:
type(a)

numpy.ndarray

In [40]:
a= np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
a= np.zeros((3,3))

In [42]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
type(a)

numpy.ndarray

In [44]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [46]:
a= np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [48]:
np.diag(a)

array([0., 0., 0.])

In [52]:
a = np.random.randint(1,100,20)
a

array([80, 37, 95, 43, 65, 66, 46, 51, 93, 39,  8, 54, 40, 84, 56, 60, 93,
       51, 47, 97])

In [54]:
a= np.arange(10)
a.dtype

dtype('int32')

In [55]:
b = np.arange(10,dtype= 'float')

In [56]:
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [57]:
c = np.zeros([3,3])

In [58]:
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [59]:
c.dtype

dtype('float64')

In [60]:
b= np.array([True,False])
b.dtype

dtype('bool')

In [61]:
k = np.array(['a','b','c'])


In [62]:
k.dtype

dtype('<U1')

In [63]:
a = np.arange(10)

In [64]:
a[5]

5

In [65]:
a = np.diag([3,3])
a

array([[3, 0],
       [0, 3]])

In [66]:
a[0,1]

0

In [67]:
#Slicing
a = np.arange(10)

In [68]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
a[1:8:2]

array([1, 3, 5, 7])

In [72]:
a[:5]

array([0, 1, 2, 3, 4])

In [73]:
a[5:]

array([5, 6, 7, 8, 9])

In [74]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
b= np.arange(5)

In [77]:
a[5:]= b[::-1]

In [78]:
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [82]:
a
b

array([0, 2, 4, 3, 1])

In [80]:
b = a[::2]


In [81]:
b

array([0, 2, 4, 3, 1])

In [83]:
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [84]:
a= np.arange(10)

In [85]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
b= np.arange(5)

In [87]:
b

array([0, 1, 2, 3, 4])

In [88]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [90]:
np.shares_memory(a,b)

True

In [91]:
b[1]=10

In [92]:
a

array([ 0,  1, 10,  3,  4,  5,  6,  7,  8,  9])

In [93]:
#Force Copy
a

array([ 0,  1, 10,  3,  4,  5,  6,  7,  8,  9])

In [95]:
c= a[::2].copy()

In [96]:
c

array([ 0, 10,  4,  6,  8])

In [97]:
np.shares_memory(a,c)

False

In [99]:
a = np.random.randint(0,20,10)
a

array([16, 15,  1,  1, 11,  8, 19,  2, 12,  6])

In [100]:
b= (a%2==0)
b

array([ True, False, False, False, False,  True, False,  True,  True,
        True])

In [101]:
c= a[b]

In [102]:
c

array([16,  8,  2, 12,  6])

In [103]:
a[b] = -1
a

array([-1, 15,  1,  1, 11, -1, 19, -1, -1, -1])

In [104]:
x = np.arange(0,100,20)

In [105]:
x

array([ 0, 20, 40, 60, 80])

In [106]:
x[[1,2]]

array([20, 40])

In [109]:
x[[1,2]]=100

In [110]:
x

array([  0, 100, 100,  60,  80])

In [111]:
a =np.array([1,2,3,4,5])
a+1

array([2, 3, 4, 5, 6])

In [112]:
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [119]:
b= np.ones(5)+1

In [120]:
b

array([2., 2., 2., 2., 2.])

In [121]:
a-b

array([-1.,  0.,  1.,  2.,  3.])

In [122]:
a

array([1, 2, 3, 4, 5])

In [124]:
m = np.diag([1,2,3])

In [125]:
m

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [126]:
m*m

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 9]])

In [127]:
m.dot(m)

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 9]])

In [128]:
#Comparision
a= np.array([1,2,3])
b= np.array([3,4,5])
a==b

array([False, False, False])

In [129]:
a<=b

array([ True,  True,  True])

In [130]:
np.array_equal(a,b)

False

In [131]:
#Logical Operation
a = np.array([1,1,0,0],dtype=bool)
b = np.array([1,0,1,0],dtype=bool)

np.logical_or(a,b)

array([ True,  True,  True, False])

In [132]:
np.logical_and(a,b)

array([ True, False, False, False])

In [133]:
#Transidential operation
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [134]:
np.log(a)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [135]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [137]:
a= np.arange(4)
a+np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [139]:
#Basic Reduction
x = np.array([1,2,3,4])
x.sum()


10

In [140]:
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [141]:
x.sum(axis=1)

array([2, 4])

In [142]:
x.sum(axis=0)

array([3, 3])

In [144]:
x.min()

1

In [145]:
x.max()

2

In [146]:
x.argmax()

2

In [148]:
np.all([True,False])

False

In [149]:
np.any([True,False])

True

In [151]:
a= np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [152]:
np.any(a!=0)

False